//! `/init` command — analyse the connected database and write starter files.
//!
//! Generates two files in the current working directory:
//!
//! * `.rpg.toml`   — project config pre-filled with the active connection
//! * `POSTGRES.md` — markdown snapshot of the database schema and settings

use std::fmt::Write as _;

use tokio_postgres::Client;

use crate::{config::Config, connection::ConnParams};

// ---------------------------------------------------------------------------
// .rpg.toml generator
// ---------------------------------------------------------------------------

/// Build the content of a `.rpg.toml` starter file.
///
/// Values from the active connection and settings are written as commented-out
/// defaults so the user can easily uncomment and customise them.
pub fn generate_rpg_toml(config: &Config, params: &ConnParams) -> String {
    let host = &params.host;
    let port = params.port;
    let dbname = &params.dbname;

    let provider = config.ai.provider.as_deref().unwrap_or("anthropic");
    let model = config
        .ai
        .model
        .as_deref()
        .unwrap_or("claude-sonnet-4-20250514");
    let border = config.display.border.unwrap_or(1);
    let pager_min_lines = config.display.pager_min_lines.unwrap_or(50);

    format!(
        r#"# Generated by rpg /init

[connection]
# host = "{host}"
# port = {port}
# dbname = "{dbname}"

[ai]
# provider = "{provider}"
# model = "{model}"
# api_key_env = "OPENAI_API_KEY" # e.g. ANTHROPIC_API_KEY, GEMINI_API_KEY, OLLAMA_API_KEY

[display]
# border = {border}
# pager_min_lines = {pager_min_lines}
"#
    )
}

// ---------------------------------------------------------------------------
// POSTGRES.md generator
// ---------------------------------------------------------------------------

/// Run a simple query and collect rows as `Vec<Vec<String>>`.
///
/// Returns `(column_names, rows)`.
async fn simple_rows(
    client: &Client,
    sql: &str,
) -> Result<(Vec<String>, Vec<Vec<String>>), String> {
    use tokio_postgres::SimpleQueryMessage;

    let messages = client
        .simple_query(sql)
        .await
        .map_err(|e| format!("query failed: {e}"))?;

    let mut col_names: Vec<String> = Vec::new();
    let mut rows: Vec<Vec<String>> = Vec::new();

    for msg in messages {
        if let SimpleQueryMessage::Row(row) = msg {
            if col_names.is_empty() {
                col_names = (0..row.len())
                    .map(|i| {
                        row.columns()
                            .get(i)
                            .map_or_else(|| format!("col{i}"), |c| c.name().to_owned())
                    })
                    .collect();
            }
            let vals: Vec<String> = (0..row.len())
                .map(|i| row.get(i).unwrap_or("").to_owned())
                .collect();
            rows.push(vals);
        }
    }

    Ok((col_names, rows))
}

/// Return the first cell of the first row, or an empty string.
fn first_cell(rows: &[Vec<String>]) -> &str {
    rows.first()
        .and_then(|r| r.first())
        .map_or("", String::as_str)
}

/// Query the database and build the content of a `POSTGRES.md` documentation
/// file.
///
/// Returns the markdown string, or an error message if any required query
/// fails.
pub async fn generate_postgres_md(client: &Client) -> Result<String, String> {
    // --- PostgreSQL version ---------------------------------------------------
    let (_, ver_rows) = simple_rows(client, "select version()").await?;
    let version_full = first_cell(&ver_rows).to_owned();
    // Trim to "PostgreSQL 17.2 on …" (first three space-separated tokens).
    let version_short = version_full
        .splitn(4, ' ')
        .take(3)
        .collect::<Vec<_>>()
        .join(" ");

    // --- Current database name -----------------------------------------------
    let (_, db_rows) = simple_rows(client, "select current_database()").await?;
    let dbname = first_cell(&db_rows).to_owned();

    // --- Database size --------------------------------------------------------
    let (_, size_rows) = simple_rows(
        client,
        "select pg_size_pretty(pg_database_size(current_database()))",
    )
    .await?;
    let db_size = convert_pg_size_to_binary(first_cell(&size_rows));

    // --- Tables --------------------------------------------------------------
    let table_sql = "\
select
    t.schemaname || '.' || t.relname as table_name,
    t.n_live_tup as row_estimate,
    pg_size_pretty(pg_total_relation_size(t.relid)) as total_size
from pg_stat_user_tables as t
order by
    pg_total_relation_size(t.relid) desc,
    t.schemaname,
    t.relname";
    let (_, table_rows) = simple_rows(client, table_sql).await?;

    // --- Extensions ----------------------------------------------------------
    let ext_sql = "\
select
    e.extname as name,
    e.extversion as version
from pg_extension as e
where e.extname != 'plpgsql'
order by e.extname";
    let (_, ext_rows) = simple_rows(client, ext_sql).await?;

    // --- Non-default settings ------------------------------------------------
    let guc_sql = "\
select
    s.name as parameter,
    s.setting as value,
    s.source as source
from pg_settings as s
where s.source not in ('default', 'override')
order by s.name";
    let (_, guc_rows) = simple_rows(client, guc_sql).await?;

    // -------------------------------------------------------------------------
    // Assemble markdown
    // -------------------------------------------------------------------------
    Ok(build_markdown(
        &dbname,
        &version_short,
        &db_size,
        &table_rows,
        &ext_rows,
        &guc_rows,
    ))
}

/// Render the gathered data as a markdown document.
fn build_markdown(
    dbname: &str,
    version_short: &str,
    db_size: &str,
    table_rows: &[Vec<String>],
    ext_rows: &[Vec<String>],
    guc_rows: &[Vec<String>],
) -> String {
    let mut md = String::new();

    let _ = writeln!(md, "# Database: {dbname}");
    md.push('\n');
    let _ = writeln!(md, "{version_short}");
    let _ = writeln!(md, "Size: {db_size}");

    // Tables section
    md.push_str("\n## Tables\n\n");
    if table_rows.is_empty() {
        md.push_str("_(no user tables)_\n");
    } else {
        md.push_str("| Table | Rows | Size |\n");
        md.push_str("|-------|------|------|\n");
        for row in table_rows {
            let name = row.first().map_or("", String::as_str);
            let rows_raw = row.get(1).map_or("0", String::as_str);
            let size_pg = row.get(2).map_or("", String::as_str);
            let rows_fmt = format_row_count(rows_raw);
            let size_bin = convert_pg_size_to_binary(size_pg);
            let _ = writeln!(md, "| {name} | {rows_fmt} | {size_bin} |");
        }
    }

    // Extensions section
    md.push_str("\n## Extensions\n\n");
    if ext_rows.is_empty() {
        md.push_str("_(no extensions installed)_\n");
    } else {
        for row in ext_rows {
            let name = row.first().map_or("", String::as_str);
            let ver = row.get(1).map_or("", String::as_str);
            let _ = writeln!(md, "- {name} {ver}");
        }
    }

    // Non-default settings section
    md.push_str("\n## Non-default Settings\n\n");
    if guc_rows.is_empty() {
        md.push_str("_(all settings at default values)_\n");
    } else {
        md.push_str("| Parameter | Value | Source |\n");
        md.push_str("|-----------|-------|--------|\n");
        for row in guc_rows {
            let param = row.first().map_or("", String::as_str);
            let val = row.get(1).map_or("", String::as_str);
            let src = row.get(2).map_or("", String::as_str);
            let _ = writeln!(md, "| {param} | {val} | {src} |");
        }
    }

    md
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Convert a `pg_size_pretty` string to binary-unit notation.
///
/// `pg_size_pretty` returns strings like `"42 MB"`, `"1536 kB"`, `"2048 bytes"`.
/// We convert to MiB / KiB / GiB / TiB per the project style guide.
/// Values already in bytes are shown as-is.
fn convert_pg_size_to_binary(pg_size: &str) -> String {
    let parts: Vec<&str> = pg_size.trim().splitn(2, ' ').collect();
    if parts.len() != 2 {
        return pg_size.to_owned();
    }
    let num_str = parts[0];
    let unit = parts[1];

    let Ok(num) = num_str.parse::<f64>() else {
        return pg_size.to_owned();
    };

    // Convert to bytes first (Postgres uses 1024-based units internally).
    let bytes: f64 = match unit {
        "bytes" => num,
        "kB" => num * 1024.0,
        "MB" => num * 1024.0 * 1024.0,
        "GB" => num * 1024.0 * 1024.0 * 1024.0,
        "TB" => num * 1024.0 * 1024.0 * 1024.0 * 1024.0,
        _ => return pg_size.to_owned(),
    };

    if bytes < 1024.0 {
        format!("{bytes:.0} bytes")
    } else if bytes < 1024.0_f64.powi(2) {
        format!("{:.0} KiB", bytes / 1024.0)
    } else if bytes < 1024.0_f64.powi(3) {
        format!("{:.1} MiB", bytes / 1024.0_f64.powi(2))
    } else if bytes < 1024.0_f64.powi(4) {
        format!("{:.1} GiB", bytes / 1024.0_f64.powi(3))
    } else {
        format!("{:.1} TiB", bytes / 1024.0_f64.powi(4))
    }
}

/// Format a row-count string with thousands separators.
fn format_row_count(s: &str) -> String {
    let Ok(n) = s.parse::<u64>() else {
        return s.to_owned();
    };
    // Insert commas every 3 digits from the right.
    let raw = n.to_string();
    let mut out = String::with_capacity(raw.len() + raw.len() / 3);
    for (i, ch) in raw.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            out.push(',');
        }
        out.push(ch);
    }
    out.chars().rev().collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_convert_pg_size_bytes() {
        assert_eq!(convert_pg_size_to_binary("512 bytes"), "512 bytes");
    }

    #[test]
    fn test_convert_pg_size_kb() {
        assert_eq!(convert_pg_size_to_binary("512 kB"), "512 KiB");
    }

    #[test]
    fn test_convert_pg_size_mb() {
        assert_eq!(convert_pg_size_to_binary("42 MB"), "42.0 MiB");
    }

    #[test]
    fn test_convert_pg_size_gb() {
        assert_eq!(convert_pg_size_to_binary("2 GB"), "2.0 GiB");
    }

    #[test]
    fn test_format_row_count_small() {
        assert_eq!(format_row_count("42"), "42");
    }

    #[test]
    fn test_format_row_count_thousands() {
        assert_eq!(format_row_count("1234"), "1,234");
    }

    #[test]
    fn test_format_row_count_millions() {
        assert_eq!(format_row_count("1234567"), "1,234,567");
    }
}
